# Generated by Django 4.1.3 on 2022-12-01 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_prep_backend', '0003_testprepparentuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('math_1', 'math_1'), ('math_2', 'math_2'), ('verbal', 'verbal'), ('reading', 'reading')], max_length=15)),
                ('start_timestamp', models.DateTimeField(auto_now_add=True)),
                ('finish_timestamp', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('responses', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('finish_timestamp', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_test_attempts', to='test_prep_backend.testprepstudentuser')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_prep_backend.test')),
            ],
        ),
        migrations.RemoveField(
            model_name='usertestattempt',
            name='test',
        ),
        migrations.RemoveField(
            model_name='usertestattempt',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserResponse',
        ),
        migrations.DeleteModel(
            name='UserTestAttempt',
        ),
        migrations.AddField(
            model_name='studentresponse',
            name='student_test_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_test_responses', to='test_prep_backend.studenttestattempt'),
        ),
    ]
