# Generated by Django 4.1.3 on 2022-12-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_prep_backend', '0004_studentresponse_studenttestattempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresponse',
            name='finish_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='responses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentresponse',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
