# Generated by Django 4.1.3 on 2022-12-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_prep_backend', '0005_alter_studentresponse_finish_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='number_of_sections',
            field=models.IntegerField(default=4),
        ),
    ]
