# Generated by Django 4.1.3 on 2023-01-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_prep_backend', '0007_studentresponse_total_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttestattempt',
            name='scores',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
