# Generated by Django 4.1.3 on 2023-01-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_prep_backend', '0008_studenttestattempt_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_limits',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
