# Generated by Django 4.1.3 on 2022-11-15 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_tracker_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('current_balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('email_primary', models.EmailField(default='acdole09@gmail.com', max_length=254)),
                ('prepayment_balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'scheduled'), ('C', 'completed'), ('X-N', 'cancelled, no charge'), ('X-C', 'cancelled, charge')], default='S', max_length=3)),
                ('date_time', models.DateTimeField()),
                ('length', models.DecimalField(decimal_places=2, default=1.0, max_digits=9)),
                ('fee', models.DecimalField(decimal_places=2, default=180.0, max_digits=9)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='tutor_tracker_backend.customer')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
