# Generated by Django 4.1.3 on 2022-11-27 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_tracker_backend', '0004_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=10000, null=True)),
                ('status', models.CharField(choices=[('I', 'In Progress'), ('S', 'Sent')], default='I', max_length=1)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_last_action', models.DateField(auto_now=True)),
                ('date_sent', models.DateField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor_tracker_backend.appointment')),
            ],
        ),
    ]
