# Generated by Django 4.1.3 on 2022-12-14 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_tracker_backend', '0006_alter_statement_date_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepayments', to='tutor_tracker_backend.customer')),
            ],
        ),
    ]
