# Generated by Django 4.1.3 on 2022-12-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_tracker_backend', '0007_prepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='source',
            field=models.CharField(choices=[('PB', 'Prepaid Balance'), ('C', 'Cash'), ('V', 'Venmo')], default='C', max_length=100),
        ),
    ]
