# Generated by Django 4.1.3 on 2023-01-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_tracker_backend', '0008_payment_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='source',
            field=models.CharField(choices=[('PB', 'Prepaid Balance'), ('C', 'Cash'), ('V', 'Venmo'), ('CC', 'Credit Card')], default='C', max_length=100),
        ),
    ]
